name: LDmanagement
favicon: null
layout_spectrum: 0.06264264974743128
typography_spectrum: 0.39581183763220906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4d7d3'
    - '#b5babe'
    - '#233557'
    - '#8e9da8'
    - '#6c8893'
  brandStrength: 0.2502960776910186
  lightness: 0.8361002358142287
  saturation: 0.7731417992617935
  rhythmicContrast: 0.8058244793210179
purpose: []
